# Generated by Django 4.0.1 on 2022-02-03 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('question', models.CharField(max_length=200, verbose_name='問題文')),
                ('q_img1', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='問題画像1')),
                ('q_img2', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='問題画像2')),
                ('q_img3', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='問題画像3')),
                ('q_img4', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='問題画像4')),
                ('answer', models.CharField(max_length=100, verbose_name='答え')),
                ('explanation', models.CharField(max_length=200, verbose_name='解説')),
                ('e_img1', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='解説画像1')),
                ('e_img2', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='解説画像2')),
                ('e_img3', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='解説画像3')),
                ('e_img4', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='解説画像4')),
                ('good', models.IntegerField(default=0, verbose_name='高評価')),
                ('bad', models.IntegerField(default=0, verbose_name='低評価')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
