# Generated by Django 4.0.2 on 2022-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hint',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ヒント'),
        ),
    ]
